MyShop.WebUI/Controllers/BasketController.cs
using MyShop.Core.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyShop.WebUI.Controllers
{
    public class BasketController : Controller
    {
        IBasketService basketService;

		public BasketController(IBasketService basketService)
		{
			this.basketService = basketService;
		}

		// GET: Basket
		public ActionResult Index()
        {
            var model = basketService.GetBasketItems(this.HttpContext);
            return View(model);
        }

        public ActionResult AddToBasket(string Id)
		{
            basketService.AddToBasket(HttpContext , Id);
            return RedirectToAction("Index");
		}

        public ActionResult RemoveFromBasket(string Id)
		{
            basketService.RemoveFromBasket(HttpContext , Id);
            return RedirectToAction("Index");

        }

        public PartialViewResult BasketSummary()
		{
            var basket = basketService.GetBasketSummary(HttpContext);
            return PartialView(basket);
		}
    }
}

MyShop.WebUI/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyShop.Core.Models;
using MyShop.DataAccess.InMemory;
using MyShop.Core.Contracts;

namespace MyShop.WebUI.Controllers
{
    public class ProductCategoryController : Controller
    {
		IRepository<ProductCategory> context;
		public ProductCategoryController(IRepository<ProductCategory> context)
		{
			this.context = context;
		}

        // GET: ProductCategory
        public ActionResult Index()
        {
            List<ProductCategory> productCategories = context.Collection().ToList();
            return View(productCategories);
        }

		#region Add Product Category
		public ActionResult Create()
		{
			ProductCategory productCategory = new ProductCategory();
			return View(productCategory);
		}

		[HttpPost]
		public ActionResult Create(ProductCategory productCategory)
		{
			if (!ModelState.IsValid)
				return View(productCategory);
			else
			{
				context.Insert(productCategory);
				context.Commit();

				return RedirectToAction("Index");
			}
		}
		#endregion

		#region Edit Product
		public ActionResult Edit(string Id)
		{
			// Fint product by ID
			var productCategory = context.Find(Id);
			if (productCategory == null)
				return HttpNotFound();
			else
				return View(productCategory);
		}

		[HttpPost]
		public ActionResult Edit(ProductCategory productCategory , string Id)
		{
			var category = context.Find(Id);
			if (category == null)
				return HttpNotFound();
			else
			{
				// Check if product is valid or not
				if (!ModelState.IsValid)
					return View(productCategory);

				//using category = productCategory will not working
				//Asign new values to current product
				category.Name = productCategory.Name;
				context.Commit();

				return RedirectToAction("Index");
			}
		}
		#endregion

		#region Delete Product
		public ActionResult Delete(string Id)
		{
			var productCategory = context.Find(Id);
			if (productCategory == null)
				return HttpNotFound();
			else
			{
				return View(productCategory);
			}
		}

		[HttpPost]
		[ActionName("Delete")]
		public ActionResult ConfirmDelete(ProductCategory productCategory , string Id)
		{
			var category = context.Find(Id);
			if (category == null)
				return HttpNotFound();
			else
			{
				context.Delete(category);
				context.Commit();

				return RedirectToAction("Index");
			}
		}
		#endregion
	}
}

MyShop.WebUI/Controllers/ProductManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyShop.Core.Models;
using MyShop.Core.ViewModels;
using MyShop.DataAccess.InMemory;
using MyShop.Core.Contracts;
using System.IO;

namespace MyShop.WebUI.Controllers
{
    public class ProductManagerController : Controller
    {
		IRepository<Product> context;
		IRepository<ProductCategory> productCategory;

		public ProductManagerController(IRepository<Product> context, IRepository<ProductCategory> productCategory)
		{
			this.context = context;
			this.productCategory = productCategory;
		}

		// GET: ProductManager
		public ActionResult Index()
        {
            List<Product> products = context.Collection().ToList();
            return View(products);
        }

		#region Add Product
		public ActionResult Create()
		{
			ProductManagerViewModel productManagerViewModel = new ProductManagerViewModel();
			productManagerViewModel.product = new Product();
			productManagerViewModel.productCategories = productCategory.Collection();
            return View(productManagerViewModel);
		}

		[HttpPost]
        public ActionResult Create(Product product, HttpPostedFileBase file) // Using HttpPostedFileBase to able to post type of submited file from html form
		{
			if (!ModelState.IsValid)
				return View(product);
			else
			{
				if(file != null)
				{
					product.Image = product.Id + Path.GetExtension(file.FileName);
					file.SaveAs(Server.MapPath("//Content//ProductImages//") + product.Image);
				}
				context.Insert(product);
				context.Commit();

				return RedirectToAction("Index");
			}
		}
		#endregion

		#region Edit Product
		public ActionResult Edit(string Id)
		{
			// Fint product by ID
			var product = context.Find(Id);
			if (product == null)
				return HttpNotFound();
			else
			{
				ProductManagerViewModel productManagerViewModel = new ProductManagerViewModel();
				productManagerViewModel.product = product;
				productManagerViewModel.productCategories = productCategory.Collection();
				return View(productManagerViewModel);
			}
		}

		[HttpPost]
		public ActionResult Edit(Product product, string Id, HttpPostedFileBase file) // Using HttpPostedFileBase to able to post type of submited file from html form
		{
			var pro = context.Find(Id);
			if (pro == null)
				return HttpNotFound();
			else
			{
				// Check if product is valid or not
				if (!ModelState.IsValid)
					return View(product);
				
				if(file != null)
				{
					pro.Image = pro.Id + Path.GetExtension(file.FileName);
					file.SaveAs(Server.MapPath("//Content//ProductImages//") + pro.Image);
				}
				//using pro = product will not working
				//Asign new values to current product
				pro.Name = product.Name;
				pro.Description = product.Description;
				pro.Category = product.Category;
				pro.Price = product.Price;
				context.Commit();

				return RedirectToAction("Index");
			}
		}
		#endregion

		#region Delete Product
		public ActionResult Delete(string Id)
		{
			var product = context.Find(Id);
			if (product == null)
				return HttpNotFound();
			else
			{
				return View(product);
			}
		}

		[HttpPost]
		[ActionName("Delete")]
		public ActionResult ConfirmDelete(Product product, string Id)
		{
			var pro = context.Find(Id);
			if (pro == null)
				return HttpNotFound();
			else
			{
				context.Delete(product);
				context.Commit();

				return RedirectToAction("Index");
			}
		}
		#endregion
	}
}

MyShop.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="p-0">
	<div>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
			<div class="container">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarTogglerDemo01">
					@Html.ActionLink("Application name" , "Index" , "Home" , new { area = "" } , new { @class = "navbar-brand" })
					<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
						<li class="nav-item active">
							@Html.ActionLink("Home" , "Index" , "Home" , new { area = "" } , new { @class = "nav-link" })
						</li>
						<li class="nav-item">
							@Html.ActionLink("Product Admin" , "Index" , "ProductManager" , new { area = "" } , new { @class = "nav-link" })
						</li>
						<li class="nav-item">
							@Html.ActionLink("Product Category" , "Index" , "ProductCategory" , new { area = "" } , new { @class = "nav-link" })
						</li>
					</ul> 

					@{
						Html.RenderAction("BasketSummary" , "Basket");
					}
					
					@Html.Partial("_LoginPartial")
				</div>
			</div>
		</nav>

		<div class="container">
			@RenderBody()
			<hr />
			<footer>
				<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
			</footer>
		</div>
	</div>



	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts" , required: false)
</body>
</html>